num = input('Digite um numero inteiro entre 0 e 9999: ')
print('O numero digitado foi: {}'.format(num))
print('Unidade: {}'.format(num[3]))
print('Dezena:  {}'.format(num[2]))
print('Centena: {}'.format(num[1]))
print('Milhar:  {}'.format(num[0]))