valor1 = input('Digite algo:')
print('O tipo primitivo desse valor é ',type(valor1))
print('Só tem espaços? ',valor1.isspace())
print('Só tem numeros?',valor1.isnumeric())
print('Só tem letras?',valor1.isalpha())
print('É letras e numeros?',valor1.isalnum())
print('Esta em maiusculas?',valor1.isupper())
print('Esta em minusculas?',valor1.islower())
print('Esta capitalizada?',valor1.istitle())
